version: '3.8'

services:
  backend:
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=${DB_USER:-admin}
      - DB_PASS=${DB_PASS:-adminpassword}
      - DB_NAME=${DB_NAME:-crm}
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=${DB_NAME:-crm}
      - MYSQL_USER=${DB_USER:-admin}
      - MYSQL_PASSWORD=${DB_PASS:-adminpassword}
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
